#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/octopus
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/mini12864-lcd
$CFGDIR/accessories/neopixels
$CFGDIR/accessories/dual-drivers-on-xy
$CFGDIR/boards/octopus_dual
#$CFGDIR/accessories/max7219-debug

# Printer's unique ID, used by some programs to differentiate between machines.
opt_set MACHINE_UUID "\"e366c46c-2094-493a-b9a9-09bd6582e5f0\""

opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 200, 200, 400 }"
opt_set DEFAULT_MAX_FEEDRATE "{ 50, 50, 4 }"

opt_enable \
    EMERGENCY_PARSER \
    REALTIME_REPORTING_COMMANDS \
    HOST_ACTION_COMMANDS

export PLATFORMIO_ENV=STM32F446ZE_btt
