#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/octopus
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/mini12864-lcd
$CFGDIR/accessories/dual-drivers-on-xy
$CFGDIR/boards/octopus_dual
#$CFGDIR/accessories/max7219-debug

# Printer's unique ID, used by some programs to differentiate between machines.
opt_set MACHINE_UUID "\"e366c46c-2094-493a-b9a9-09bd6582e5f0\""

opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 200, 200, 400 }"
opt_set DEFAULT_MAX_FEEDRATE "{ 50, 50, 4 }"

opt_enable \
    EMERGENCY_PARSER \
    REALTIME_REPORTING_COMMANDS \
    HOST_ACTION_COMMANDS

# TMC2209 drivers for all steppers
opt_set X_DRIVER_TYPE "TMC2209"
opt_set Y_DRIVER_TYPE "TMC2209"
opt_set Z_DRIVER_TYPE "TMC2209"
opt_set X2_DRIVER_TYPE "TMC2209"
opt_set Y2_DRIVER_TYPE "TMC2209"

# TMC Settings
opt_set HOLD_MULTIPLIER 0.8
opt_set X_CURRENT  725
opt_set Y_CURRENT  725
opt_set Z_CURRENT  650
opt_set X2_CURRENT 650
opt_set Y2_CURRENT 650

opt_enable \
    STEALTHCHOP_XY \
    STEALTHCHOP_Z \
    STEALTHCHOP_E

export PLATFORMIO_ENV=STM32F446ZE_btt
