#!/bin/bash

# This script adds logos and names to the configs.

opt_set STRING_CONFIG_H_AUTHOR "\"(Collab, Thijs, ${V1_VERSION})\""

# opt_set won't work, because it isn't in the configuration or configuration_adv.h, so we're going to
# just put it into the Configuration.h

echo "#define SHORT_BUILD_VERSION \"${V1_VERSION} ${MARLIN_VERSION}\"" >> Marlin/Configuration.h
echo "#define DIAG_JUMPERS_REMOVED" >> Marlin/Configuration.h
echo "#define NO_AUTO_ASSIGN_WARNING" >> Marlin/Configuration.h

opt_enable \
    DIRECT_PIN_CONTROL \
    LONG_FILENAME_HOST_SUPPORT \
    LONG_FILENAME_WRITE_SUPPORT \
    EEPROM_AUTO_INIT

opt_disable \
    EVENT_GCODE_SD_ABORT

# Add custom boot and status screens
cp $CFGDIR/common/_Bootscreen.h Marlin/
opt_enable SHOW_CUSTOM_BOOTSCREEN

# Total duration to display the boot screen (ms)
opt_set BOOTSCREEN_TIMEOUT 3000

cp $CFGDIR/common/_Statusscreen.h Marlin/
opt_enable CUSTOM_STATUS_SCREEN_IMAGE

# Start by putting the machine config and the marlin version in the readme
echo "# ${CONFIG_NAME} - ${MARLIN_VERSION} - ${V1_VERSION}" > README.md
cat $CFGDIR/common/Readme_header.md >> README.md
